# Use Node image with Alpine for smaller size
FROM node:22-alpine

# Set working dir
WORKDIR /app

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy all frontend source
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start frontend in dev mode
CMD ["npm", "run", "dev"]