services:
  postgres:                             #service name
    image: postgres:16                  #official postgresql v16 image
    container_name: webhook_pipeline_db #name of the running container
    restart: always                     #automatically restart if container stops
    environment:                        #env variables used by postgres
      POSTGRES_USER: postgres           
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"                     #map container port -> host port
    volumes:
      - postgres_data:/var/lib/postgresql/data #persist database files 

  api:                                  #Node.js API service
    build: .                            #build container from Dockerfile in project root
    container_name: webhook_pipeline_api #name of the running API container
    restart: always                     #restart API if it crashes
    depends_on:
      - postgres                        #ensure postgres starts before API
    ports:
      - "8080:8080"                     #expose API to localhost:8080
    env_file:
      - .env.docker                            #load environment variables from .env.docker

  worker:
    build: .
    container_name: webhook_pipeline_worker
    restart: always
    env_file:
      - .env.docker                     # uses env.docker because db host must be postgres
    command: ["npm", "run", "worker"]   #run worker. It needs its own command because it must run npm run worker instead of the API server
    depends_on:
      - postgres

volumes:
  postgres_data:                        #named volume docker manages for persistent storage


#both api and worker should use env.docker because they run inside docker containers, not on my machine.
#Inside Docker,containers communicate over the Docker network using service names as hostnames, so db_host should be postgres
#because i defined it above. Basically Docker compose lets other containers reach that service by its name